FPS = 60
RES = WIDTH, HEIGHT = 800, 560
SURF_RES = SURF_WIDTH, SURF_HEIGHT = 640, 480

TILES_SHAPE = N_ROWS, N_COLS = 16, 20

TILE_WIDTH = SURF_WIDTH // N_COLS
TILE_HEIGHT = SURF_HEIGHT // N_ROWS

POSSIBLE_TILE_STATES = ["wall", "path"]
SURF_POS_CORDS = (WIDTH - SURF_WIDTH) // 2, (HEIGHT - SURF_HEIGHT) // 2